language: java

dist: xenial

jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true # Travis idea of install doesn't fit here

before_script: travis_retry mvn -B help:active-profiles

script: travis_retry mvn -B verify -Pits -Dinvoker.streamLogs=true -Dinvoker.debug=false

addons:
   apt:
      packages:
         - rpm
